import type { Metadata } from "next";
import { Inter as interFonts } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import { wagmi } from "@/config";
import { Web3ModalProvider } from "@/context";
import { Web3Connect } from "@/components";

const inter = interFonts({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(wagmi.config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider initialState={initialState}>
          <h3>layout header</h3>
          <Web3Connect />
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
